### ISSUE TITLE
Dungeons and Villages trapped in mountains

### ISSUE THREAD

**Issue by cambragol** [Fenyx4/U4DosRandomizer#11]
This is for the lastest: Release v0.1-alpha.4

I found that some dungeons, and perhaps a village? were 'trapped', nearly or fully, within mountains.

Is this the correct place for this type of feedback? I assume so as you are releasing alpha builds, for testing..correct?

![Ultima IV Randomized 2020-09-01 at 5 13 49 PM](https://user-images.githubusercontent.com/5019739/91825184-df027e00-ec76-11ea-8fa3-cbc87950cb76.png)
![Ultima IV Randomized 2020-09-01 at 5 13 43 PM](https://user-images.githubusercontent.com/5019739/91825189-e164d800-ec76-11ea-8551-b18757af81d0.png)

**Comment by Fenyx4** [comment]
Yeah this is the perfect place for feedback! I'm very excited you are using it!

Just committed a fix for this; https://github.com/Fenyx4/U4DosRandomizer/commit/1d61496d289ff27bc557a3280ff40f79e9ff27cb

Basically I make sure everything paths back to a town and since the towns all path to a moongate that SHOULD mean everything is reachable.

Unfortunately I did make some changes so you'll won't be able to generate the same map in this new version.

Thank you for letting me know about the bug!

**Comment by Fenyx4** [comment]
P.S. If you find any other bugs like this the program should write out a seed.txt file. If you include that in the bug report along with the version then I can recreate the map (and bug) locally.
