### ISSUE TITLE
Blinking into the Abyss Valley

### ISSUE THREAD

**Issue by cambragol** [Fenyx4/U4DosRandomizer#28]
In the original it is quite difficult to 'blink' into the Abyss valley. I'm not sure if it is possible, but I couldn't manage it. (Though in the Apple II version I seem to remember pulling it off)

Probably because it looks like the whole bottom right corner of the map is off limits to blink from tile 192 on in the x and y coordinates

This little piece in u4_spell.c:

		if((Party._x & Party._y) < 0xc0) {

However, it is possible in the randomized version:

![Ultima IV Randomized 2020-09-06 at 9 57 37 PM](https://user-images.githubusercontent.com/5019739/92326478-92131300-f08d-11ea-8c2f-677fe577fdad.png)

**Comment by Fenyx4** [comment]
Well fiddlesticks. If the blink exclusion zone had an upperbound I could just move it.

I suppose I could shift the entire world so Abyss Valley is always in the southeast.... But might just be time to make some actual code edits to AVATAR.EXE.

**Comment by Fenyx4** [comment]
I recoded Avatar.exe so I could move the exclusion zone but due to some strangeness of how blink works it still allows blinking inside Abyss Valley in specific circumstances.

So I can either limit the locations the Abyss can go, change the shape of the exclusion zone or change how the exclusion zone works so it blocks people so it excludes people blinking into it instead of blocking people casting the spell. (Which is a subtle difference but gives me more control.)

I am worried about increasing the size as even with the current size it is weird having spots you can't blink. Fine in the original game since it is all water and mountain.

So I am leaning towards changing it to exclude where people can blink to. 

Thoughts?

**Comment by cambragol** [comment]
Excluding where they can blink to should be relatively easy, if avatar.exe is being modified. Sounds good.

A third option would be to make the randomization of the map always place the abyss onto a mysterious hidden island somewhere. Throw in the shrine of humility and Hythloth too, but in a new random arrangement. Familiar but new.

**Comment by Fenyx4** [comment]
Shiny. I'll work on the excluding.

Yeah, I've been thinking about tossing it on an island. But it would require a surprising number of changes to how I have some stuff setup. And it could still get placed somewhere that could get blinked into if I'm not careful.

**Comment by Fenyx4** [comment]
This will be fixed with the next release! You can no longer blink into the Abyss or to the shrine of Humility.
