### ISSUE TITLE
Compatibility with VGA/Music and EGA downgrade patches

### ISSUE THREAD

**Issue by Fenyx4** [Fenyx4/U4DosRandomizer#64]

**Comment by nleseul** [comment]
So, in a binary compare of the AVATAR.EXE produced by the VGA/MIDI patch and the original file, the only difference I see is that the patch modifies a couple of lists of the rune image filenames (to support unique images for each virtue). 

I successfully applied the randomizer to a VGA/MIDI patched folder by simply removing the patched AVATAR.EXE and restoring the original, and the game seemed to run fine for the couple hours that I played it (the VOD is on my channel). I'd assume the only issue would be that you'd see the wrong rune images if you got elevated in a virtue, which I didn't get to test.

I don't know what the best way to set up the randomizer code to handle that slight difference would be, but it probably won't be too difficult.

**Comment by Fenyx4** [comment]
You played it?! And there is a VOD?! *runs off to watch*

**Comment by Fenyx4** [comment]
Ermagerd I love your shirt!
Playing on a MiSTer? Awesome!

**Comment by Fenyx4** [comment]
https://github.com/Fenyx4/U4DosRandomizer/issues/107 <- New task for "Other" option
I actually had it coded up really early on in the process before I thought I was going to be making any changes to the code. But then lost the changes. And I keep forgetting to add a new task for it.

**Comment by Fenyx4** [comment]
I don't have dungeons tucked away behind mountains yet sadly. It is on my want to do list. But no idea when I'd get to it.

(Just gonna end up commenting on your entire stream in here. <3 )

**Comment by Fenyx4** [comment]
It is the original layout of the forest battle map.
But there is a card to randomize those https://github.com/Fenyx4/U4DosRandomizer/issues/92

**Comment by Fenyx4** [comment]
Can you expand on your idea for enhancing the telescope?

**Comment by Fenyx4** [comment]
Finding the Spirituality shrine outside of the moongate is a bug that has been fixed but the fix hasn't been released yet. *embarassed*

https://github.com/Fenyx4/U4DosRandomizer/commit/39516bb662f68cb4512331f9ed7bef3fc3c81b12

**Comment by nleseul** [comment]
> Can you expand on your idea for enhancing the telescope?

Basically, the vanilla telescope works by showing you a gem view of any of the towns or castles, based on a map index from A-P. That's not terribly useful in a randomizer, since people playing a randomizer probably have the vanilla towns mostly memorized anyway. It would be really useful in a randomizer, though, if you could specify a region of the world map using sextant coordinates and see a gem view of that region. That way, if you found the Lycaeum before finding a source of gems, you'd have another way to survey the world map for points of interest. 

It might not be feasible, though, depending on how complicated the world map paging is. You might not be able to get the map loaded to display a gem for it while you're in a castle.
